#!/bin/sh
sudo apt-get update -y
sudo apt-get install apache2 -y

echo '<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Storage</title>
  </head>
  <body>
    </pecho $hostname>
    <img src="https://storage.cloud.google.com/sup_kykilebg/supdevinci-logo.png">
  </body>
</html>
| sudo tee /var/www/html/index.html
